USE [master]
GO
/****** Object:  Database [BabiloDB]    Script Date: 05-06-2022 22:42:54 ******/
CREATE DATABASE [BabiloDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BabiloDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\BabiloDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BabiloDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\BabiloDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [BabiloDB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BabiloDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BabiloDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BabiloDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BabiloDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BabiloDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BabiloDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [BabiloDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BabiloDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BabiloDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BabiloDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BabiloDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BabiloDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BabiloDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BabiloDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BabiloDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BabiloDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [BabiloDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BabiloDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BabiloDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BabiloDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BabiloDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BabiloDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BabiloDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BabiloDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [BabiloDB] SET  MULTI_USER 
GO
ALTER DATABASE [BabiloDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BabiloDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BabiloDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BabiloDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [BabiloDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [BabiloDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [BabiloDB] SET QUERY_STORE = OFF
GO
USE [BabiloDB]
GO
/****** Object:  Table [dbo].[Admin_Registration]    Script Date: 05-06-2022 22:42:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Admin_Registration](
	[adminId] [int] NOT NULL,
	[password] [varchar](18) NOT NULL,
	[name] [varchar](20) NOT NULL,
	[EmailId] [varchar](50) NOT NULL,
	[phoneNumber] [varchar](20) NULL,
 CONSTRAINT [PK_Admin_REGISTRATION] PRIMARY KEY CLUSTERED 
(
	[adminId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Auditorium_Registration]    Script Date: 05-06-2022 22:42:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Auditorium_Registration](
	[auditoriumId] [int] NOT NULL,
	[auditoriumName] [varchar](18) NOT NULL,
	[auditoriumLocation] [varchar](20) NOT NULL,
	[movieId] [varchar](50) NOT NULL,
	[seatAvailable] [int] NULL,
 CONSTRAINT [PK_Auditorium_REGISTRATION] PRIMARY KEY CLUSTERED 
(
	[auditoriumId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Movie_Registration]    Script Date: 05-06-2022 22:42:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Movie_Registration](
	[movieId] [int] NOT NULL,
	[movieName] [varchar](18) NOT NULL,
	[movieDirector] [varchar](20) NOT NULL,
	[movieRating] [int] NOT NULL,
	[moviePrice] [decimal](18, 2) NULL,
 CONSTRAINT [PK_Movie_REGISTRATION] PRIMARY KEY CLUSTERED 
(
	[movieId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[User_Registration]    Script Date: 05-06-2022 22:42:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User_Registration](
	[userId] [int] NOT NULL,
	[password] [varchar](18) NOT NULL,
	[name] [varchar](20) NOT NULL,
	[EmailId] [varchar](50) NOT NULL,
	[phoneNumber] [varchar](20) NULL,
 CONSTRAINT [PK_User_REGISTRATION] PRIMARY KEY CLUSTERED 
(
	[userId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [BabiloDB] SET  READ_WRITE 
GO
